apiVersion: v2
name: vaultls-agent
description: Keeps VaulTLS certificates in Kubernetes Secrets, ready to be replicated to other namespaces
type: application
version: 0.2.1
appVersion: "0.4.1"
home: https://github.com/vasyakrg/VaulTLS
sources:
  - https://github.com/vasyakrg/VaulTLS
keywords:
  - tls
  - certificates
  - pki
